name: Check

on:
  #push:
  pull_request:
  #schedule:
  #    -   cron:  '0 3 * * *'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        dotnet: [7.0.305]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore tools
        run: dotnet tool restore

      - name: Run tests
        run: ./build.sh

  tests:
    strategy:
      matrix:
        dotnet: [7.0.305]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore tools
        run: dotnet tool restore

      - name: Run tests
        run: ./build.sh -t tests
